# Generated by Django 4.1 on 2022-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_descriptions_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_descriptions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
