# Generated by Django 4.1 on 2022-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_slug_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='password1',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
