# Generated by Django 4.1 on 2022-10-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='products',
            new_name='product',
        ),
    ]
